// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as proxy$0 from "./proxy/models.js";

/**
 * ClearLogs clears all logs
 */
export function ClearLogs(): $CancellablePromise<void> {
    return $Call.ByID(1566804265);
}

/**
 * GetCurrentEncoding returns the current encoding setting
 */
export function GetCurrentEncoding(): $CancellablePromise<string> {
    return $Call.ByID(2582793309);
}

/**
 * GetCurrentHTMLVersion returns the current HTML version
 */
export function GetCurrentHTMLVersion(): $CancellablePromise<string> {
    return $Call.ByID(3681988759);
}

/**
 * GetCurrentImageFormat returns the current image format setting
 */
export function GetCurrentImageFormat(): $CancellablePromise<string> {
    return $Call.ByID(2754399882);
}

/**
 * GetEncodings returns the available encoding options for the dropdown
 */
export function GetEncodings(): $CancellablePromise<proxy$0.EncodingOption[] | null> {
    return $Call.ByID(3131466263);
}

/**
 * GetHTMLVersions returns available HTML version options
 */
export function GetHTMLVersions(): $CancellablePromise<proxy$0.HTMLVersionOption[] | null> {
    return $Call.ByID(1951479159);
}

/**
 * GetImageFormats returns available image format options
 */
export function GetImageFormats(): $CancellablePromise<proxy$0.ImageFormatOption[] | null> {
    return $Call.ByID(233451388);
}

/**
 * GetLaunchAtStartup reports whether the application is registered to launch
 * when the current user signs in.
 */
export function GetLaunchAtStartup(): $CancellablePromise<boolean> {
    return $Call.ByID(2697658);
}

/**
 * GetLogs returns recent log messages
 */
export function GetLogs(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1743981476);
}

/**
 * GetStatus returns the current server status
 */
export function GetStatus(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1043986649);
}

/**
 * IsDebugMode returns whether debug mode is enabled
 */
export function IsDebugMode(): $CancellablePromise<boolean> {
    return $Call.ByID(1845811523);
}

/**
 * IsRunning returns whether the proxy server is running
 */
export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(1670839396);
}

/**
 * SetDebugMode enables or disables debug mode
 */
export function SetDebugMode(enabled: boolean): $CancellablePromise<string> {
    return $Call.ByID(3682936569, enabled);
}

/**
 * SetEncoding sets the forced encoding (or "auto" for auto-detect)
 */
export function SetEncoding(encoding: string): $CancellablePromise<string> {
    return $Call.ByID(3521705002, encoding);
}

/**
 * SetHTMLVersion sets the HTML version simplifier
 */
export function SetHTMLVersion(version: string): $CancellablePromise<string> {
    return $Call.ByID(2564614842, version);
}

/**
 * SetImageFormat sets the image format
 */
export function SetImageFormat(format: string): $CancellablePromise<string> {
    return $Call.ByID(1637755811, format);
}

/**
 * SetLaunchAtStartup updates the operating system's per-user startup entry.
 */
export function SetLaunchAtStartup(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(749774982, enabled);
}

/**
 * ShowMainWindow restores the main application window from the taskbar, Dock,
 * or tray and brings it to the foreground.
 */
export function ShowMainWindow(): $CancellablePromise<void> {
    return $Call.ByID(3189675457);
}

/**
 * StartProxy starts the proxy server on the specified port
 */
export function StartProxy(port: number): $CancellablePromise<string> {
    return $Call.ByID(2835838209, port);
}

/**
 * StopProxy stops the proxy server
 */
export function StopProxy(): $CancellablePromise<string> {
    return $Call.ByID(3345047379);
}
