// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EncodingOption represents an encoding option for the UI
 */
export interface EncodingOption {
    "value": string;
    "label": string;
}

/**
 * HTMLVersionOption represents an HTML version option
 */
export interface HTMLVersionOption {
    "value": string;
    "label": string;
}

/**
 * ImageFormatOption represents an image format option for the UI
 */
export interface ImageFormatOption {
    "value": string;
    "label": string;
}
