// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proxy} from '../models';

export function ClearLogs():Promise<void>;

export function GetCurrentEncoding():Promise<string>;

export function GetCurrentHTMLVersion():Promise<string>;

export function GetCurrentImageFormat():Promise<string>;

export function GetEncodings():Promise<Array<proxy.EncodingOption>>;

export function GetHTMLVersions():Promise<Array<proxy.HTMLVersionOption>>;

export function GetImageFormats():Promise<Array<proxy.ImageFormatOption>>;

export function GetLogs():Promise<Array<string>>;

export function GetStatus():Promise<Record<string, any>>;

export function IsDebugMode():Promise<boolean>;

export function IsRunning():Promise<boolean>;

export function SetDebugMode(arg1:boolean):Promise<string>;

export function SetEncoding(arg1:string):Promise<string>;

export function SetHTMLVersion(arg1:string):Promise<string>;

export function SetImageFormat(arg1:string):Promise<string>;

export function StartProxy(arg1:number):Promise<string>;

export function StopProxy():Promise<string>;
