// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function GetCurrentEncoding() {
  return window['go']['main']['App']['GetCurrentEncoding']();
}

export function GetCurrentHTMLVersion() {
  return window['go']['main']['App']['GetCurrentHTMLVersion']();
}

export function GetCurrentImageFormat() {
  return window['go']['main']['App']['GetCurrentImageFormat']();
}

export function GetEncodings() {
  return window['go']['main']['App']['GetEncodings']();
}

export function GetHTMLVersions() {
  return window['go']['main']['App']['GetHTMLVersions']();
}

export function GetImageFormats() {
  return window['go']['main']['App']['GetImageFormats']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function IsDebugMode() {
  return window['go']['main']['App']['IsDebugMode']();
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function SetDebugMode(arg1) {
  return window['go']['main']['App']['SetDebugMode'](arg1);
}

export function SetEncoding(arg1) {
  return window['go']['main']['App']['SetEncoding'](arg1);
}

export function SetHTMLVersion(arg1) {
  return window['go']['main']['App']['SetHTMLVersion'](arg1);
}

export function SetImageFormat(arg1) {
  return window['go']['main']['App']['SetImageFormat'](arg1);
}

export function StartProxy(arg1) {
  return window['go']['main']['App']['StartProxy'](arg1);
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}
